name: Virtual PC Online

on:
  workflow_dispatch:
    inputs:
      access_password:
        description: 'Defina a senha de acesso da máquina'
        required: true
        default: '123456'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configurar Senha do Usuário
        run: |
          echo "runner:${{ github.event.inputs.access_password }}" | sudo chpasswd
          sudo usermod -aG sudo runner

      - name: Instalar Área de Trabalho e Servidor RDP
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-goodies xrdp
          sudo adduser xrdp ssl-cert
          echo "xfce4-session" > ~/.xsession
          sudo systemctl start xrdp

      - name: Instalar e Conectar ao Tailscale
        run: |
          AUTH_KEY="${{ secrets.TAISSCALE_AUTH_KEY }}"
          if [ -z "$AUTH_KEY" ]; then
            echo "::error::A Secret TAISSCALE_AUTH_KEY não foi encontrada!"
            exit 1
          fi
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey="$AUTH_KEY" --hostname=github-runner

      - name: Manter a Máquina Ativa
        run: |
          echo "PC Virtual pronto para RDP (RD Client)!"
          sudo tailscale ip -4
          sleep infinity
          
