name: Windows 11 Virtual PC

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Instalar e Conectar ao Tailscale
        run: |
          AUTH_KEY="${{ secrets.TAISSCALE_AUTH_KEY }}"
          if [ -z "$AUTH_KEY" ]; then
            echo "::error::A Secret TAISSCALE_AUTH_KEY não foi encontrada!"
            exit 1
          fi
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey="$AUTH_KEY" --hostname=github-runner

      - name: Iniciar o Windows 11 no Docker
        run: |
          sudo docker run -d \
            --name windows11 \
            --device=/dev/kvm \
            --cap-add=NET_ADMIN \
            -p 3389:3389/tcp \
            -e RAM_SIZE="4G" \
            -e CPU_CORES="2" \
            -e USERNAME="runner" \
            -e PASSWORD="123456" \
            dockur/windows

      - name: Manter a Máquina Ativa e Mostrar IP
        run: |
          echo "=========================================="
          echo "Aguarde de 3 a 5 minutos até o Windows 11 iniciar!"
          echo "Seu IP do Tailscale é:"
          sudo tailscale ip -4
          echo "=========================================="
          sleep infinity
